### ISSUE TITLE
Previous version developed by Anshuman and Manraj is missing

### ISSUE THREAD

**Issue by manrajgrover** [NSITulator/NSITulatorWeb#1]
README.md needs updating. Should I send a PR for it?

**Comment by uditarora** [comment]
Sure, please do.

**Comment by uditarora** [comment]
Thanks for the update. Closing the issue.

**Comment by bogas04** [comment]
Fixed by https://github.com/NSITulator/NSITulatorWeb/commit/3555d1546e3cd6026658e47b01fc0ca09a5261be
