### ISSUE TITLE
Allow calculation of 7th and 8th Sem result

### ISSUE THREAD

**Issue by manrajgrover** [NSITulator/NSITulatorWeb#5]
I can take this one up. Why isn't it already supported?

**Comment by uditarora** [comment]
It's supported for the branches for which I found the data about subject categories.
If you have the data for other branches please let me know so that it can be added.

**Comment by manrajgrover** [comment]
@uditarora I guess curriculum has changed starting this year. Should we wait for updates on that? We do  have it available [here](http://v2.collegespace.in/academics-2/syllabus/)

**Comment by uditarora** [comment]
@ManrajGrover I've seen these PDFs. They don't have subject category information for all branches after 6th sem. That is why calculation for those branches isn't supported.

**Comment by manrajgrover** [comment]
@uditarora Just checked. Link I shared does contain that information.

**Comment by uditarora** [comment]
Fixed by a2b419b
