### ISSUE TITLE
Dropping only takes 4 credit subject

### ISSUE THREAD

**Issue by prabhakar267** [NSITulator/NSITulatorWeb#8]
While dropping subjects, college can also drop two subjects of 2 credits each instead of one 4 credits subject.

**Comment by uditarora** [comment]
Yes, in the final result they even drop 1-credit and 3-credit courses. However the problem with implementing this is that the categories for non-4 credit courses aren't mentioned in the syllabus.

But this is the formula TnP used (at least till I was in college) for calculating percentage of students after dropping, ie, only dropping 4-credit courses based on categories.

**Comment by prabhakar267** [comment]
Maybe we can provide both the scores, along with the little tooltip explaining the difference in percentage.

**Comment by uditarora** [comment]
I think it'll be too random, and lead to more confusion than solving any problems. At least right now we have consistent calculations.
